In [2]:
import praw
import pandas as pd

In [3]:
client_id = 'BDg7LZGq0FZknQ'
secret = 'UIX3BDNYvqcYaSi3dAI3joZPeMs'
name = 'Jayesh Vasudeva'

In [4]:
reddit = praw.Reddit(client_id=client_id, client_secret=secret, user_agent=name)

In [5]:
subred = ['india']
posts = []
for r in subred:
    subreddit = reddit.subreddit(r).hot(limit=20000)
    for post in subreddit:
        posts.append([post.title, post.selftext, post.link_flair_text, post.score])
    table = pd.DataFrame(posts,columns=['title', 'body', 'flair', 'score'])
        
#         prints the titile of the post
#         print("title: ",post.title)
#         prints the number of upvotes for a post
#         print("score: ",post.score)
#         prints the body of the post
#         print("body: ",post.selftext)
#         prints the url of the post
#         print("url: ",post.url)
#         prints the flair of the post
#         print("flair: ",post.link_flair_text)

In [6]:
table

,title,body,flair,score
0,Kashmir News Coverage - 3,A summary of news coverage on Kashmir in the p...,Politics,150
1,Chandrayaan Moon Landing,ISRO's Chandrayaan 2 mission is a significant ...,[R]eddiquette,383
2,Isro loses contact with Chandrayaan-2 lander: ...,,Science/Technology,545
3,"PM fulfils promise, 8 crore poor families get ...",,Policy/Economy,221
4,What ISRO Chief Said After Loss Of Contact Wit...,,Science/Technology,112
...,...,...,...,...
759,Help for Non-CS engineers.,I see so many posts on r/india which deal with...,Science/Technology,8
760,"""All But Sharad Pawar, Prithviraj Chavan Will ...",,Politics,18
761,Every Third Indian Cop Thinks Mob Violence Ove...,,[R]eddiquette,218
762,'Every world leader has discussed yoga',,Politics,2642
763,Weekly photography thread thread - September 0...,This is a weekly scheduled thread for all the ...,Scheduled,22

In [7]:
table = table.sample(frac=1)
table

,title,body,flair,score
566,‘Torture chambers’ present at more Kerala govt...,,Policy/Economy,85
464,"10 Killed, Many Trapped After Explosion At Fir...",,Non-Political,15
83,"9,000 houses get notices from Chennai Corp to ...",,Policy/Economy,175
11,"In J&K, terrorists use posters to fight agains...",,Politics,35
183,Karnataka HC raps govt for not implementing no...,,Policy/Economy,22
...,...,...,...,...
409,GDP growth at 5%: P Chidambaram slams Narendra...,,Policy/Economy,3
285,P Chidambaram sent to Tihar jail till Sept 19 ...,,Politics,25
410,Intelligence Failure led to Pulwama Terror Att...,,Policy/Economy,67
60,Romila Thapar Declines to Send her CV to JNU,,Politics,103
121,Madras HC CJ Tahilramani Likely To Resign,,Politics,6

In [8]:
table.to_csv("data.csv")